### ISSUE TITLE
No output when using watch

### ISSUE THREAD

**Issue by luebken** [kubecolor/kubecolor#186]
### Expected behavior

(Duplicate of https://github.com/kubecolor/kubecolor/issues/107 but it's closed) 

shows color
```
kubecolor get pods
```
doesn't show color: 
```
watch --color kubecolor get pods
```

### Package manager

Homebrew

### What operating system are you running?

MacOS

### Kubectl and kubecolor version

```yaml
kubecolor --kubecolor-version
v0.4.0
```
```
kubectl version
Client Version: v1.31.1
```

**Comment by applejag** [comment]
Hello @luebken! Thanks for reporting this. Sadly, when running inside `watch` kubecolor can't figure out if the output has color support or not. What you have to do is to force it to use colors like so:

```bash
watch --color kubecolor get pods --force-colors
```

If you're making use of truecolor color codes in your themes then you can force kubecolor to use that (due to it falling back to basic ANSI when just specifying `--force-colors`, read more: <https://kubecolor.github.io/usage/how-it-works/#dynamic-color-support>):

```bash
watch --color kubecolor get pods --force-colors=truecolor
```

**Comment by applejag** [comment]
Going to close this as "Won't do" as we can't really do anything about this.
